version: "3.9"
services:
  database:
      container_name: database_mysql
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony_docker
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql
  backend:
    container_name: api_symfony 
    build:
      context: ./api
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/symfony_docker
    depends_on:
      - database
  webserver:
    container_name: nginx_webserver
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./api:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - database
    networks:
          default:
              aliases:
                  - api.endpoint
  frontend:
    container_name: react_app
    build:
      context: ./react-app
    ports:
      - "3039:3000"
    stdin_open: true
    volumes:
       - ./react-app:/usr/src/app/react-app
       - /usr/src/app/react-app/node_modules
    environment:
      - WDS_SOCKET_PORT=0
    
  